import type {Metadata} from "next";
import "./globals.css";
import {TodoProvider} from "@/contexts/TodoContext";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
    <body>
    <main>
      <TodoProvider>
        {children}
      </TodoProvider>
    </main>
    </body>
    </html>
  );
}
